FROM gitlabdr.clb.nl:5050/embedded/w-serie/w1700/yocto-platforms/wamm_platform/sdk_image:latest

RUN echo "source /usr/local/oecore-x86_64/environment-setup-cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi" >> /root/.bashrc

SHELL  ["/bin/bash", "-c"]
